[dev]
port = 8888 # The port that the netlify dev will be accessible on
targetPort=4000

[build]
  base = "apps/web"
  publish = "apps/web/.next"
  command = "npm run build"
  functions = "apps/web/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200